### ISSUE TITLE
Correct regexp for study IDs?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/peyotl#118]
In my refactoring I've found what looks like two separate regular expressions used to validate study IDs. The [ID_PATTERN in `git_actions.py`](https://github.com/OpenTreeOfLife/peyotl/blob/master/peyotl/phylesystem/git_actions.py#L14) is strict in allowing exactly two letters and one underscore, while the [STUDY_ID_PATTERN in `phylesystem_umbrella.py`](https://github.com/OpenTreeOfLife/peyotl/blob/master/peyotl/phylesystem/phylesystem_umbrella.py#L35) allows any number of letters in the prefix, and any number of underscores before the numeric part. 

I'd like to consolidate to just one of these, unless there's a distinction that I'm missing. The former (stricter) regexp seems more like what we expect in the current phylesystem, yes? Just want to make sure before messing with this.

**Comment by jimallman** [comment]
Ah, I see that [`get_filepath_for_namespaced_id `](https://github.com/OpenTreeOfLife/peyotl/blob/c5457ee292afc10bdcbc460410e8de1c3b339a51/peyotl/phylesystem/git_actions.py#L51-L65) assumes a two-letter prefix and a single underscore. On that basis, I'll go ahead with the more restrictive regexp above. Please close this issue, or let me know if this is a bad idea.

**Comment by jar398** [comment]
My two cents:

At the beginning of the new ids we (or at least I) talked about the study
ids being CURIEs (http://www.w3.org/TR/rdfa-core/#s_curies) with the colon
changed to an underscore so that they could be used as file names. This
would permit a natural translation to URLs for use in RDF.

This is not to say that all unambiguous CURIEs (those without an _) should
be usable as study ids, but the closer they are to one another, the fewer
surprises there will be.

I think restricting to two letters is kind of silly.  The prefix should be
allowed to be any ncname that doesn't contain underscores.

I can see that we are committed to having the last two characters of the
part after the _ be digits, so for simplicity we should probably have all
the characters after the _ be digits (meaning unfortunately that we don't
have QNAMEs by changing _ to :.

**Comment by mtholder** [comment]
2 letters is arbitrary, but it will be easy to revisit this if we intentionally move away from 2 letter prefixes. I guess I'd say that, for the time being, we should consolidate to the 2 letter regex if we are still using both regex patterns.
