### ISSUE TITLE
testChangedStudies failing after collections changes

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/peyotl#136]
When running the maintainer tests:
```
======================================================================
FAIL: testChangedStudies (peyotl.test.test_phylesystem.TestPhylesystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karen/Documents/opentreeoflife/software/peyotl/peyotl/test/test_phylesystem.py", line 52, in testChangedStudies
    self.assertEqual(set(['xy_13', 'xy_10']), changed)
AssertionError: Items in the first set but not the second:
'xy_13'
'xy_10'

----------------------------------------------------------------------
```

**Comment by jimallman** [comment]
The test doesn't match the history of this test repo; we're looking for studies that have changed since the **most recent commit**, which will always be empty. The previous SHA fits the bill, and substituting that satisfies all tests. I'll make a tiny PR with this, but first I want to review the older tests to see why this worked before. :confused:

**Comment by jimallman** [comment]
Actually, I've added this commit (a32ef8177fed7ccb962991f30cb98328238f3a44) to the existing PR. @mtholder, please review the commit message to see if I'm getting this right.

**Comment by mtholder** [comment]
fixed
