### ISSUE TITLE
single values vs lists for same property

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/peyotl#147]
I don't know if this is the right location for this issue, but trying anyway. 

For cases where a nexson property can be a single item or a list, is there a good reason not to always have it be a list? For example, compare `ot:curator` in [pg_1102](https://github.com/OpenTreeOfLife/phylesystem-1/blob/master/study/pg_02/pg_1102/pg_1102.json#L123) (list) with [pg_710](https://github.com/OpenTreeOfLife/phylesystem-1/blob/master/study/pg_10/pg_710/pg_710.json#L46) (string). I can work around this, but it would make database querying much simpler if it were always a list. This holds for `ot:tag` as well (and possibly other properties).

**Comment by mtholder** [comment]
that is the convention that badgerfish uses. We don't have to follow that, but it does allow the nexson validator to be pretty much a syntax checker (rather than having to know much about the different tags).
I don't strenuously object to changing that, but I have not looked into how much work it would be.

**Comment by kcranston** [comment]
Ok, good to know. I'll investigate further.

**Comment by kcranston** [comment]
Turns out that 'working around this' was trivial.
